version: '3.8'
services:
  oracle-xe: # <.>
    environment:
      - ORACLE_PASSWORD=oracle
    image: gvenzl/oracle-free # <.>
    ports:
      - "1521:1521"
    restart: unless-stopped
    volumes:
      - oracle-volume:/opt/oracle/oradata # <.>
      - ./src/init:/container-entrypoint-initdb.d # <.>
    healthcheck:
      test: [ "CMD", "healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 10

  oracle-sqlcl: # <.>
    image: container-registry.oracle.com/database/sqlcl:latest # <.>
    volumes:
      - ./sql_scripts:/opt/oracle/sql_scripts/
    depends_on:
      oracle-xe:
        condition: service_healthy
    stdin_open: true
    tty: true
    links:
      - oracle-xe:oracle-xe # <.>
volumes:
  oracle-volume: